demo3/demo3/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('', include('vote.urls', namespace='vote'))
]

demo3/vote/urls.py
from django.conf.urls import url
from .views import ListViews, DetailViews, ResultViews, LoginViews, \
    RegistViews, LogoutViews, ActiveView, CheckUsernameView, VerifyView
app_name = 'vote'

urlpatterns = [
    url(r'^list/$', ListViews.as_view(), name='list'),
    url(r'^detail/(\d+)/$', DetailViews.as_view(), name='detail'),
    url(r'^result/(\d+)/$', ResultViews.as_view(), name='result'),
    url(r'^login/$', LoginViews.as_view(), name='login'),
    url(r'^regist/$', RegistViews.as_view(), name='regist'),
    url(r'^logout/$', LogoutViews.as_view(), name='logout'),
    url(r'^active/(.*?)/$', ActiveView.as_view(), name='active'),
    url(r'^checkusername/$', CheckUsernameView.as_view(), name='checkusername'),
    url(r'^verify/$', VerifyView.as_view(), name='verify'),
]

demo3/vote/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Problem(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Answer(models.Model):
    choice = models.CharField(max_length=20)
    count = models.IntegerField(default=0)
    relation = models.ForeignKey(Problem, on_delete=models.CASCADE)

    def __str__(self):
        return self.choice


class MyUser(User):

    telephone = models.CharField(max_length=11)

demo3/vote/forms.py
from django import forms
from .models import MyUser
from django.utils.translation import gettext_lazy


# class LoginForm(forms.Form):
#     # 定义表单中的邮件字段
#     email = forms.EmailField(label="邮箱", widget=forms.EmailInput(attrs={"id": "email", "class": "form-control", "placeholder": "请输入邮箱"}))
#     username = forms.CharField(label="用户名", max_length=15, min_length=6, widget=forms.TextInput(attrs={"id": "username", "class": "form-control", "placeholder": "请输入用户名"}))
#     password = forms.CharField(label="密码", max_length=15, min_length=6, widget=forms.PasswordInput(attrs={"id": "password", "class": "form-control", "placeholder": "请输入密码"}))


class MyUserLoginForm(forms.ModelForm):

    class Meta():
        model = MyUser
        fields = ['username', 'password']
        widgets = {
            "username": forms.TextInput(attrs={'class': 'form-control'}),
            "password": forms.PasswordInput(attrs={'class': 'form-control'})
        }
        help_texts = {'username': gettext_lazy('')}


class MyUserRegistForm(forms.ModelForm):

    class Meta():
        model = MyUser
        fields = ['username', 'password', 'email']
        widgets = {
            "username": forms.TextInput(attrs={'class': 'form-control'}),
            "password": forms.PasswordInput(attrs={'class': 'form-control'}),
            "email": forms.EmailInput(attrs={'class': 'form-control'}),
        }
        help_texts = {'username': gettext_lazy('')}

demo3/vote/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .models import Problem, Answer, MyUser
from django.views.generic import View
from .forms import MyUserLoginForm, MyUserRegistForm
from django.contrib.auth import login, logout, authenticate
from django.core.mail import EmailMultiAlternatives
from itsdangerous import TimedJSONWebSignatureSerializer
from django.conf import settings
from PIL import Image, ImageDraw, ImageFont
import random, io
# Create your views here.


def checklogin(fun):
    def check(self, req, *args):
        # if req.COOKIES.get("username"):
        # if req.session.get('username'):
        #     return fun(self, req, *args)
        if req.user and req.user.is_authenticated:
            return fun(self, req, *args)
        else:
            return redirect(reverse("vote:login"))
    return check


class ListViews(View):

    @checklogin
    def get(self, req):
        problems = Problem.objects.all()
        return render(req, 'vote/list.html', locals())


class DetailViews(View):

    @checklogin
    def get(self, req, id):
        problem = Problem.objects.get(pk=id)
        return render(req, 'vote/detail.html', locals())

    @checklogin
    def post(self, req, id):
        a_id = req.POST.get('res')
        a = Answer.objects.get(pk=a_id)
        a.count += 1
        a.save()
        return redirect(reverse('vote:result', args=(id,)))


class ResultViews(View):

    @checklogin
    def get(self, req, id):
        problem = Problem.objects.get(pk=id)
        return render(req, 'vote/result.html', locals())


class LoginViews(View):

    def get(self, req):
        lf = MyUserLoginForm()
        rf = MyUserRegistForm()
        return render(req, 'vote/login.html', locals())

    def post(self, req):

        username = req.POST.get('username')
        password = req.POST.get('password')
        verify = req.POST.get('verify')
        # user = authenticate(req, username=username, password=password)
        user = MyUser.objects.filter(username=username)
        if user:
            if user[0].check_password(password):
                if user[0].is_active:
                    # if verify == req.session.get('verifycode'):
                    from django.core.cache import cache
                    if verify == cache.get('verifycode'):

                        user1 = authenticate(req, username=username, password=password)
                        login(req, user1)
                        return redirect(reverse('vote:list'))
                    else:
                        lf = MyUserLoginForm()
                        rf = MyUserRegistForm()
                        errormessage = '验证码错误'
                        return render(req, 'vote/login.html', locals())
                else:
                    lf = MyUserLoginForm()
                    rf = MyUserRegistForm()
                    errormessage = '用户尚未激活'
                    return render(req, 'vote/login.html', locals())
            else:
                lf = MyUserLoginForm()
                rf = MyUserRegistForm()
                errormessage = '密码错误'
                return render(req, 'vote/login.html', locals())

        else:
            lf = MyUserLoginForm()
            rf = MyUserRegistForm()
            errormessage = '用户名不存在'
            return render(req, 'vote/login.html', locals())

        # res = redirect(reverse('vote:list'))
        # res.set_cookie('username', username)
        # return res
        # req.session['username'] = username

        # lf = LoginForm(req.POST)
        # print(lf.is_valid())
        # print(lf.cleaned_data['email'])
        # print(lf.cleaned_data['username'])
        # print(lf.cleaned_data['password'])
        # return redirect(reverse('vote:list'))


class RegistViews(View):

    def get(self, req):
        pass

    def post(self, req):
        try:
            username = req.POST.get('username')
            password = req.POST.get('password')
            email = req.POST.get('email')
            user = MyUser.objects.create_user(username=username, email=email, password=password)
            user.is_active = False
            user.save()
            userid = user.id
            from django.conf import settings
            util = TimedJSONWebSignatureSerializer(secret_key=settings.SECRET_KEY)
            userid = util.dumps({'userid': userid}).decode('utf-8')
            info = '请激活<a href="http://127.0.0.1:8000/active/%s/"> 点我激活%s</a>' % (userid, username,)
            from django.conf import settings
            mail = EmailMultiAlternatives("请激活", info, settings.DEFAULT_FROM_EMAIL, [email])
            mail.content_subtype = 'html'
            mail.send()
            if user:
                return redirect(reverse('vote:login'))

        except:
            lf = MyUserLoginForm()
            rf = MyUserRegistForm()
            errormessage = '注册失败'
            return render(req, 'vote/login.html', locals())


class LogoutViews(View):
    def get(self, req):
        logout(req)
        return redirect(reverse('vote:login'))


class ActiveView(View):

    def get(self, req, id):

        util = TimedJSONWebSignatureSerializer(secret_key=settings.SECRET_KEY)
        obj = util.loads(id)
        id = obj['userid']
        user = MyUser.objects.filter(pk=id).first()
        if user:
            user.is_active = True
            user.save()
            return redirect(reverse('vote:login'))


class CheckUsernameView(View):

    def get(self, req):
        username = req.GET.get('username')
        user = MyUser.objects.filter(username=username).first()
        if user:
            return JsonResponse({'statecode': 1})
        else:
            return JsonResponse({'statecode': 0, 'error': '用户名不存在'})


class VerifyView(View):

    def get(self, req):

        # 定义变量，用于画面的背景色、宽、高
        bgcolor = (random.randrange(20, 100),
                   random.randrange(20, 100),
                   random.randrange(20, 100))
        width = 100
        heigth = 25
        # 创建画面对象
        im = Image.new('RGB', (width, heigth), bgcolor)
        # 创建画笔对象
        draw = ImageDraw.Draw(im)

        # 调用画笔的point()函数绘制噪点
        for i in range(0, 100):
            xy = (random.randrange(0, width), random.randrange(0, heigth))
            fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
            draw.point(xy, fill=fill)

        # 定义验证码的备选值
        str1 = 'ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ0'
        # 随机选取4个值作为验证码
        rand_str = ''
        for i in range(0, 4):
            rand_str += str1[random.randrange(0, len(str1))]
        # 构造字体对象
        font = ImageFont.truetype('calibrib.ttf', 23)
        fontcolor = (255, random.randrange(0, 255), random.randrange(0, 255))
        # 绘制4个字
        draw.text((5, 2), rand_str[0], font=font, fill=fontcolor)
        draw.text((25, 2), rand_str[1], font=font, fill=fontcolor)
        draw.text((50, 2), rand_str[2], font=font, fill=fontcolor)
        draw.text((75, 2), rand_str[3], font=font, fill=fontcolor)
        # 释放画笔
        del draw
        # req.session['verifycode'] = rand_str
        from django.core.cache import cache
        cache.set('verifycode', rand_str, 300)
        f = io.BytesIO()
        im.save(f, 'png')
        # 将内存中的图片数据返回给客户端，MIME类型为图片png
        return HttpResponse(f.getvalue(), 'image/png')

demo3/templates/vote/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    <title>base</title>
    {% endblock %}

    {% block link %}
    {% endblock %}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>

    {% block script %}
    {% endblock %}
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

demo3/templates/vote/detail.html
{% extends 'vote/base.html' %}

{% block title %}
<title>详情页</title>
{% endblock %}

{% block body %}
    {{ problem.title }}
    <ul>
        <form action="{% url 'vote:detail' problem.id %}" method="post">
            {% for a in problem.answer_set.all %}

            {% if forloop.counter == 1 %}

            <li><input type="radio" checked name="res" value="{{ a.id }}"> {{ a.choice }}</li>

            {% else %}

            <li><input type="radio" name="res" value="{{ a.id }}"> {{ a.choice }}</li>

            {% endif %}

            {% endfor %}
            <input type="submit" value="提交">
        </form>
    </ul>
{% endblock %}

demo3/templates/vote/list.html
{% extends 'vote/base.html' %}

{% block title %}
<title>列表页</title>
{% endblock %}

{% block body %}
    {% if request.user and request.user.is_authenticated %}
        <h3>当前用户为 {{ request.user }} <a href="{% url 'vote:logout' %}">退出</a>  </h3>
    {% endif %}
    <h3>问题列表</h3>

    {% if problems %}
    <ul>
        {% for problem in problems %}
            <li>
                <a href="{% url 'vote:detail' problem.id %}">{{ problem.title }}</a>
                <a href="{% url 'vote:result' problem.id %}">查看结果</a>
            </li>
        {% endfor %}

    </ul>
    {% else %}
    没有书
    {% endif %}
{% endblock %}

demo3/templates/vote/login.html
{% extends 'vote/base.html' %}

{% block title %}
<title>login</title>
{% endblock %}

{% block script %}
    <script>
        $(function(){
            $("#id_username").blur(function(){
                $.ajax({
                    type: 'get',
                    url: '/checkusername/?username=' + $("#id_username").val(),
                    success: function(data){
                        console.log(data);
                        if(data['statecode']==0){
                            $('#errorinfo').text(data['error'])
                        }
                    }
                })

            });
            $("#myimg").click(function(){
                $('#myimg').attr('src', '/verify/?t=' + new Date().getTime())
            })
        })
    </script>
{% endblock %}



{% block body %}
    <form action="#" method="post">
        <h3>{{ errormessage }}</h3>
        <div>

          <!-- Nav tabs -->
          <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#login" aria-controls="login" role="tab" data-toggle="tab">登录</a></li>
            <li role="presentation"><a href="#regist" aria-controls="regist" role="tab" data-toggle="tab">注册</a></li>
          </ul>

          <!-- Tab panes -->
          <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="login">
                <form action="{% url 'vote:login' %}" method="post">
                    <li id="errorinfo"></li>
                    {% csrf_token %}
                    {{ lf }}
                    <label for="id_verify">验证码:</label><img id="myimg" src="{% url 'vote:verify' %}" alt="">
                    <input type="text" name="verify" class="form-control" maxlength="150" required="" id="id_verify">
                    <button type="submit">登录</button>
                </form>
            </div>
            <div role="tabpanel" class="tab-pane" id="regist">
                <form action="{% url 'vote:regist' %}" method="post">
                    {% csrf_token %}
                    {{ rf }}
                    <button type="submit">注册</button>
                </form>
            </div>
          </div>

        </div>
    </form>
{% endblock %}




{% comment %}
{% block body %}
    <form action="#" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">用户名：</label>
            <input name="username" type="text" class="form-control" id="username" placeholder="请输入用户名">
        </div>
        <div class="form-group">
            <label for="password">密码：</label>
            <input name="password" type="password" class="form-control" id="password" placeholder="请输入密码">
        </div>

        <button type="submit" class="btn btn-default">登录</button>
    </form>

<br><br>
    <form action="#" method="post">
        {% csrf_token %}
        {{ lf }}

        <button type="submit" class="btn btn-default">登录</button>
    </form>
{% endblock %}
{% endcomment %}

demo3/templates/vote/result.html
{% extends 'vote/base.html' %}

{% block title %}
<title>结果页</title>
{% endblock %}

{% block link %}
<link rel="stylesheet" href="static/css/main.css">
{% endblock %}

{% block body %}

    <h3>{{ problem.title }}</h3>
    {% for a in problem.answer_set.all %}

        {{ a.choice }}:{{ a.count }}票
    <br>
    {% endfor %}
    <a href="{% url 'vote:list' %}">返回</a>
{% endblock %}